/*
 * https,//gist.github.com/sthobis
 * source, https,//ctrlq.org/code/19899-google-translate-languages
 */

export const LanguageObject = {
  af: "Afrikaans",
  sq: "Albanian",
  ar: "Arabic",
  az: "Azerbaijani",
  eu: "Basque",
  bn: "Bengali",
  be: "Belarusian",
  bg: "Bulgarian",
  ca: "Catalan",
  "zh-CN": "Chinese Simplified",
  "zh-TW": "Chinese Traditional",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  en: "English",
  eo: "Esperanto",
  et: "Estonian",
  tl: "Filipino",
  fi: "Finnish",
  fr: "French",
  gl: "Galician",
  ka: "Georgian",
  de: "German",
  el: "Greek",
  gu: "Gujarati",
  ht: "Haitian Creole",
  iw: "Hebrew",
  hi: "Hindi",
  hu: "Hungarian",
  is: "Icelandic",
  id: "Indonesian",
  ga: "Irish",
  it: "Italian",
  ja: "Japanese",
  kn: "Kannada",
  ko: "Korean",
  la: "Latin",
  lv: "Latvian",
  lt: "Lithuanian",
  mk: "Macedonian",
  ms: "Malay",
  mt: "Maltese",
  no: "Norwegian",
  fa: "Persian",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  sr: "Serbian",
  sk: "Slovak ",
  sl: "Slovenian",
  es: "Spanish",
  sw: "Swahili",
  sv: "Swedish",
  ta: "Tamil",
  te: "Telugu ",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
  cy: "Welsh",
  yi: "Yiddish",
};

export const LANGUAGES = [
  { code: "af", lang: "Afrikaans" },
  { code: "sq", lang: "Albanian" },
  { code: "ar", lang: "Arabic" },
  { code: "az", lang: "Azerbaijani" },
  { code: "eu", lang: "Basque" },
  { code: "bn", lang: "Bengali" },
  { code: "be", lang: "Belarusian" },
  { code: "bg", lang: "Bulgarian" },
  { code: "ca", lang: "Catalan" },
  { code: "zh-CN", lang: "Chinese Simplified" },
  { code: "zh-TW", lang: "Chinese Traditional" },
  { code: "hr", lang: "Croatian" },
  { code: "cs", lang: "Czech" },
  { code: "da", lang: "Danish" },
  { code: "nl", lang: "Dutch" },
  { code: "en", lang: "English" },
  { code: "eo", lang: "Esperanto" },
  { code: "et", lang: "Estonian" },
  { code: "tl", lang: "Filipino" },
  { code: "fi", lang: "Finnish" },
  { code: "fr", lang: "French" },
  { code: "gl", lang: "Galician" },
  { code: "ka", lang: "Georgian" },
  { code: "de", lang: "German" },
  { code: "el", lang: "Greek" },
  { code: "gu", lang: "Gujarati" },
  { code: "ht", lang: "Haitian Creole" },
  { code: "iw", lang: "Hebrew" },
  { code: "hi", lang: "Hindi" },
  { code: "hu", lang: "Hungarian" },
  { code: "is", lang: "Icelandic" },
  { code: "id", lang: "Indonesian" },
  { code: "ga", lang: "Irish" },
  { code: "it", lang: "Italian" },
  { code: "ja", lang: "Japanese" },
  { code: "kn", lang: "Kannada" },
  { code: "ko", lang: "Korean" },
  { code: "la", lang: "Latin" },
  { code: "lv", lang: "Latvian" },
  { code: "lt", lang: "Lithuanian" },
  { code: "mk", lang: "Macedonian" },
  { code: "ms", lang: "Malay" },
  { code: "mt", lang: "Maltese" },
  { code: "no", lang: "Norwegian" },
  { code: "fa", lang: "Persian" },
  { code: "pl", lang: "Polish" },
  { code: "pt", lang: "Portuguese" },
  { code: "ro", lang: "Romanian" },
  { code: "ru", lang: "Russian" },
  { code: "sr", lang: "Serbian" },
  { code: "sk", lang: "Slovak " },
  { code: "sl", lang: "Slovenian" },
  { code: "es", lang: "Spanish" },
  { code: "sw", lang: "Swahili" },
  { code: "sv", lang: "Swedish" },
  { code: "ta", lang: "Tamil" },
  { code: "te", lang: "Telugu" },
  { code: "th", lang: "Thai" },
  { code: "tr", lang: "Turkish" },
  { code: "uk", lang: "Ukrainian" },
  { code: "ur", lang: "Urdu" },
  { code: "vi", lang: "Vietnamese" },
  { code: "cy", lang: "Welsh" },
  { code: "yi", lang: "Yiddish" },
];

// http://country.io/names.json


export const DailingCode = {
  BD: "+880",
  BE: "+32",
  BF: "+226",
  BG: "+359",
  BA: "+387",
  BB: "+246",
  WF: "+681",
  BL: "+590",
  BM: "+441",
  BN: "+673",
  BO: "+591",
  BH: "+973",
  BI: "+257",
  BJ: "+229",
  BT: "+975",
  JM: "+876",
  BW: "+267",
  WS: "+685",
  BQ: "+599",
  BR: "+55",
  BS: "+242",
  JE: "+44",
  BY: "+375",
  BZ: "+501",
  RU: "+7",
  RW: "+250",
  RS: "+381",
  TL: "+670",
  RE: "+262",
  TM: "+993",
  TJ: "+992",
  RO: "+40",
  TK: "+690",
  GW: "+245",
  GT: "+502",
  GR: "+30",
  GQ: "+240",
  GP: "+590",
  JP: "+81",
  GY: "+592",
  GG: "+44",
  GF: "+594",
  GE: "+995",
  GD: "+473",
  GB: "+44",
  GA: "+241",
  SV: "+503",
  GN: "+224",
  GM: "+220",
  GL: "+299",
  GI: "+350",
  GH: "+233",
  OM: "+968",
  TN: "+216",
  JO: "+962",
  HR: "+385",
  HT: "+509",
  HU: "+36",
  HK: "+852",
  HN: "+504",
  VE: "+58",
  PS: "+970",
  PW: "+680",
  PT: "+351",
  SJ: "+47",
  PY: "+595",
  IQ: "+964",
  PA: "+507",
  PF: "+689",
  PG: "+675",
  PE: "+51",
  PK: "+92",
  PH: "+63",
  PN: "+64",
  PL: "+48",
  PM: "+508",
  ZM: "+260",
  EH: "+212",
  EE: "+372",
  EG: "+20",
  ZA: "+27",
  EC: "+593",
  IT: "+39",
  VN: "+84",
  SB: "+677",
  ET: "+251",
  SO: "+252",
  ZW: "+263",
  SA: "+966",
  ES: "+34",
  ER: "+291",
  ME: "+382",
  MD: "+373",
  MG: "+261",
  MF: "+590",
  MA: "+212",
  MC: "+377",
  UZ: "+998",
  MM: "+95",
  ML: "+223",
  MO: "+853",
  MN: "+976",
  MH: "+692",
  MK: "+389",
  MU: "+230",
  MT: "+356",
  MW: "+265",
  MV: "+960",
  MQ: "+596",
  MR: "+222",
  IM: "+670",
  UG: "+256",
  TZ: "+255",
  MY: "+60",
  MX: "+52",
  IL: "+972",
  FR: "+33",
  IO: "+246",
  SH: "+290",
  FI: "+358",
  FJ: "+679",
  FK: "+500",
  FM: "+691",
  FO: "+298",
  NI: "+505",
  NL: "+31",
  NO: "+47",
  NA: "+264",
  VU: "+678",
  NC: "+687",
  NE: "+227",
  NF: "+672",
  NG: "+234",
  NZ: "+64",
  NP: "+977",
  NR: "+674",
  NU: "+683",
  CK: "+682",
  CI: "+225",
  CH: "+41",
  CO: "+57",
  CN: "+86",
  CM: "+237",
  CL: "+56",
  CC: "+61",
  CA: "+1",
  CG: "+242",
  CF: "+236",
  CD: "+243",
  CZ: "+420",
  CY: "+357",
  CX: "+61",
  CR: "+506",
  CW: "+599",
  CV: "+238",
  CU: "+53",
  SZ: "+268",
  SY: "+963",
  SX: "+599",
  KG: "+996",
  KE: "+254",
  SS: "+211",
  SR: "+597",
  KI: "+686",
  KH: "+855",
  KM: "+269",
  ST: "+239",
  SK: "+421",
  KR: "+82",
  SI: "+386",
  KP: "+850",
  KW: "+965",
  SN: "+221",
  SM: "+378",
  SL: "+232",
  SC: "+248",
  KZ: "+7",
  KY: "+345",
  SG: "+65",
  SE: "+46",
  SD: "+249",
  DJ: "+253",
  DK: "+45",
  VG: "+284",
  DE: "+49",
  YE: "+967",
  DZ: "+213",
  US: "+1",
  UY: "+598",
  YT: "+262",
  UM: "+1",
  LB: "+961",
  LC: "+758",
  LA: "+856",
  TV: "+688",
  TW: "+886",
  TT: "+262",
  TR: "+90",
  LK: "+94",
  LI: "+423",
  LV: "+371",
  TO: "+676",
  LT: "+370",
  LU: "+352",
  LR: "+231",
  LS: "+266",
  TH: "+66",
  TG: "+228",
  TD: "+235",
  LY: "+218",
  VA: "+379",
  AE: "+971",
  AD: "+376",
  AF: "+93",
  IS: "+354",
  IR: "+98",
  AM: "+374",
  AL: "+355",
  AO: "+244",
  AR: "+54",
  AU: "+61",
  AT: "+43",
  AW: "+297",
  IN: "+91",
  AX: "+358",
  AZ: "+994",
  IE: "+353",
  ID: "+62",
  UA: "+380",
  QA: "+974",
  MZ: "+258",
};

export const CountryCode = [
  { countryCode: "BD", countryName: "Bangladesh" },
  { countryCode: "BE", countryName: "Belgium" },
  { countryCode: "BF", countryName: "Burkina Faso" },
  { countryCode: "BG", countryName: "Bulgaria" },
  { countryCode: "BA", countryName: "Bosnia and Herzegovina" },
  { countryCode: "BB", countryName: "Barbados" },
  { countryCode: "BM", countryName: "Bermuda" },
  { countryCode: "BN", countryName: "Brunei" },
  { countryCode: "BO", countryName: "Bolivia" },
  { countryCode: "BH", countryName: "Bahrain" },
  { countryCode: "BI", countryName: "Burundi" },
  { countryCode: "BJ", countryName: "Benin" },
  { countryCode: "BT", countryName: "Bhutan" },
  { countryCode: "BW", countryName: "Botswana" },
  { countryCode: "WF", countryName: "Wallis and Futuna" },
  { countryCode: "BL", countryName: "Saint Barthelemy" },
  { countryCode: "JM", countryName: "Jamaica" },
  { countryCode: "WS", countryName: "Samoa" },
  { countryCode: "BQ", countryName: "Bonaire, Saint Eustatius and Saba " },
  { countryCode: "BR", countryName: "Brazil" },
  { countryCode: "BS", countryName: "Bahamas" },
  { countryCode: "JE", countryName: "Jersey" },
  { countryCode: "BY", countryName: "Belarus" },
  { countryCode: "BZ", countryName: "Belize" },
  { countryCode: "RU", countryName: "Russia" },
  { countryCode: "RW", countryName: "Rwanda" },
  { countryCode: "RS", countryName: "Serbia" },
  { countryCode: "TL", countryName: "East Timor" },
  { countryCode: "RE", countryName: "Reunion" },
  { countryCode: "TM", countryName: "Turkmenistan" },
  { countryCode: "TJ", countryName: "Tajikistan" },
  { countryCode: "RO", countryName: "Romania" },
  { countryCode: "TK", countryName: "Tokelau" },
  { countryCode: "GW", countryName: "Guinea-Bissau" },
  { countryCode: "GT", countryName: "Guatemala" },
  { countryCode: "GR", countryName: "Greece" },
  { countryCode: "GQ", countryName: "Equatorial Guinea" },
  { countryCode: "GP", countryName: "Guadeloupe" },
  { countryCode: "JP", countryName: "Japan" },
  { countryCode: "GY", countryName: "Guyana" },
  { countryCode: "GG", countryName: "Guernsey" },
  { countryCode: "GF", countryName: "French Guiana" },
  { countryCode: "GE", countryName: "Georgia" },
  { countryCode: "GD", countryName: "Grenada" },
  { countryCode: "GB", countryName: "United Kingdom" },
  { countryCode: "GA", countryName: "Gabon" },
  { countryCode: "SV", countryName: "El Salvador" },
  { countryCode: "GN", countryName: "Guinea" },
  { countryCode: "GM", countryName: "Gambia" },
  { countryCode: "GL", countryName: "Greenland" },
  { countryCode: "GI", countryName: "Gibraltar" },
  { countryCode: "GH", countryName: "Ghana" },
  { countryCode: "OM", countryName: "Oman" },
  { countryCode: "TN", countryName: "Tunisia" },
  { countryCode: "JO", countryName: "Jordan" },
  { countryCode: "HR", countryName: "Croatia" },
  { countryCode: "HT", countryName: "Haiti" },
  { countryCode: "HU", countryName: "Hungary" },
  { countryCode: "HK", countryName: "Hong Kong" },
  { countryCode: "HN", countryName: "Honduras" },
  { countryCode: "VE", countryName: "Venezuela" },
  { countryCode: "PS", countryName: "Palestinian Territory" },
  { countryCode: "PW", countryName: "Palau" },
  { countryCode: "PT", countryName: "Portugal" },
  { countryCode: "SJ", countryName: "Svalbard and Jan Mayen" },
  { countryCode: "PY", countryName: "Paraguay" },
  { countryCode: "IQ", countryName: "Iraq" },
  { countryCode: "PA", countryName: "Panama" },
  { countryCode: "PF", countryName: "French Polynesia" },
  { countryCode: "PG", countryName: "Papua New Guinea" },
  { countryCode: "PE", countryName: "Peru" },
  { countryCode: "PK", countryName: "Pakistan" },
  { countryCode: "PH", countryName: "Philippines" },
  { countryCode: "PN", countryName: "Pitcairn" },
  { countryCode: "PL", countryName: "Poland" },
  { countryCode: "PM", countryName: "Saint Pierre and Miquelon" },
  { countryCode: "ZM", countryName: "Zambia" },
  { countryCode: "EH", countryName: "Western Sahara" },
  { countryCode: "EE", countryName: "Estonia" },
  { countryCode: "EG", countryName: "Egypt" },
  { countryCode: "ZA", countryName: "South Africa" },
  { countryCode: "EC", countryName: "Ecuador" },
  { countryCode: "IT", countryName: "Italy" },
  { countryCode: "VN", countryName: "Vietnam" },
  { countryCode: "SB", countryName: "Solomon Islands" },
  { countryCode: "ET", countryName: "Ethiopia" },
  { countryCode: "SO", countryName: "Somalia" },
  { countryCode: "ZW", countryName: "Zimbabwe" },
  { countryCode: "SA", countryName: "Saudi Arabia" },
  { countryCode: "ES", countryName: "Spain" },
  { countryCode: "ER", countryName: "Eritrea" },
  { countryCode: "ME", countryName: "Montenegro" },
  { countryCode: "MD", countryName: "Moldova" },
  { countryCode: "MG", countryName: "Madagascar" },
  { countryCode: "MF", countryName: "Saint Martin" },
  { countryCode: "MA", countryName: "Morocco" },
  { countryCode: "MC", countryName: "Monaco" },
  { countryCode: "UZ", countryName: "Uzbekistan" },
  { countryCode: "MM", countryName: "Myanmar" },
  { countryCode: "ML", countryName: "Mali" },
  { countryCode: "MO", countryName: "Macao" },
  { countryCode: "MN", countryName: "Mongolia" },
  { countryCode: "MH", countryName: "Marshall Islands" },
  { countryCode: "MK", countryName: "Macedonia" },
  { countryCode: "MU", countryName: "Mauritius" },
  { countryCode: "MT", countryName: "Malta" },
  { countryCode: "MW", countryName: "Malawi" },
  { countryCode: "MV", countryName: "Maldives" },
  { countryCode: "MQ", countryName: "Martinique" },
  { countryCode: "MR", countryName: "Mauritania" },
  { countryCode: "IM", countryName: "Isle of Man" },
  { countryCode: "UG", countryName: "Uganda" },
  { countryCode: "TZ", countryName: "Tanzania" },
  { countryCode: "MY", countryName: "Malaysia" },
  { countryCode: "MX", countryName: "Mexico" },
  { countryCode: "IL", countryName: "Israel" },
  { countryCode: "FR", countryName: "France" },
  { countryCode: "IO", countryName: "British Indian Ocean Territory" },
  { countryCode: "SH", countryName: "Saint Helena" },
  { countryCode: "FI", countryName: "Finland" },
  { countryCode: "FJ", countryName: "Fiji" },
  { countryCode: "FK", countryName: "Falkland Islands" },
  { countryCode: "FM", countryName: "Micronesia" },
  { countryCode: "FO", countryName: "Faroe Islands" },
  { countryCode: "NI", countryName: "Nicaragua" },
  { countryCode: "NL", countryName: "Netherlands" },
  { countryCode: "NO", countryName: "Norway" },
  { countryCode: "NA", countryName: "Namibia" },
  { countryCode: "VU", countryName: "Vanuatu" },
  { countryCode: "NC", countryName: "New Caledonia" },
  { countryCode: "NE", countryName: "Niger" },
  { countryCode: "NF", countryName: "Norfolk Island" },
  { countryCode: "NG", countryName: "Nigeria" },
  { countryCode: "NZ", countryName: "New Zealand" },
  { countryCode: "NP", countryName: "Nepal" },
  { countryCode: "NR", countryName: "Nauru" },
  { countryCode: "NU", countryName: "Niue" },
  { countryCode: "CK", countryName: "Cook Islands" },
  { countryCode: "CI", countryName: "Ivory Coast" },
  { countryCode: "CH", countryName: "Switzerland" },
  { countryCode: "CO", countryName: "Colombia" },
  { countryCode: "CN", countryName: "China" },
  { countryCode: "CM", countryName: "Cameroon" },
  { countryCode: "CL", countryName: "Chile" },
  { countryCode: "CC", countryName: "Cocos Islands" },
  { countryCode: "CA", countryName: "Canada" },
  { countryCode: "CG", countryName: "Republic of the Congo" },
  { countryCode: "CF", countryName: "Central African Republic" },
  { countryCode: "CD", countryName: "Democratic Republic of the Congo" },
  { countryCode: "CZ", countryName: "Czech Republic" },
  { countryCode: "CY", countryName: "Cyprus" },
  { countryCode: "CX", countryName: "Christmas Island" },
  { countryCode: "CR", countryName: "Costa Rica" },
  { countryCode: "CW", countryName: "Curacao" },
  { countryCode: "CV", countryName: "Cape Verde" },
  { countryCode: "CU", countryName: "Cuba" },
  { countryCode: "SZ", countryName: "Swaziland" },
  { countryCode: "SY", countryName: "Syria" },
  { countryCode: "SX", countryName: "Sint Maarten" },
  { countryCode: "KG", countryName: "Kyrgyzstan" },
  { countryCode: "KE", countryName: "Kenya" },
  { countryCode: "SS", countryName: "South Sudan" },
  { countryCode: "SR", countryName: "Suriname" },
  { countryCode: "KI", countryName: "Kiribati" },
  { countryCode: "KH", countryName: "Cambodia" },
  { countryCode: "KM", countryName: "Comoros" },
  { countryCode: "ST", countryName: "Sao Tome and Principe" },
  { countryCode: "SK", countryName: "Slovakia" },
  { countryCode: "KR", countryName: "South Korea" },
  { countryCode: "SI", countryName: "Slovenia" },
  { countryCode: "KP", countryName: "North Korea" },
  { countryCode: "KW", countryName: "Kuwait" },
  { countryCode: "SN", countryName: "Senegal" },
  { countryCode: "SM", countryName: "San Marino" },
  { countryCode: "SL", countryName: "Sierra Leone" },
  { countryCode: "SC", countryName: "Seychelles" },
  { countryCode: "KZ", countryName: "Kazakhstan" },
  { countryCode: "KY", countryName: "Cayman Islands" },
  { countryCode: "SG", countryName: "Singapore" },
  { countryCode: "SE", countryName: "Sweden" },
  { countryCode: "SD", countryName: "Sudan" },
  { countryCode: "DO", countryName: "Dominican Republic" },
  { countryCode: "DJ", countryName: "Djibouti" },
  { countryCode: "DK", countryName: "Denmark" },
  { countryCode: "VG", countryName: "British Virgin Islands" },
  { countryCode: "DE", countryName: "Germany" },
  { countryCode: "YE", countryName: "Yemen" },
  { countryCode: "DZ", countryName: "Algeria" },
  { countryCode: "US", countryName: "United States" },
  { countryCode: "UY", countryName: "Uruguay" },
  { countryCode: "YT", countryName: "Mayotte" },
  { countryCode: "UM", countryName: "United States Minor Outlying Islands" },
  { countryCode: "LB", countryName: "Lebanon" },
  { countryCode: "LC", countryName: "Saint Lucia" },
  { countryCode: "LA", countryName: "Laos" },
  { countryCode: "TV", countryName: "Tuvalu" },
  { countryCode: "TW", countryName: "Taiwan" },
  { countryCode: "TT", countryName: "Trinidad and Tobago" },
  { countryCode: "TR", countryName: "Turkey" },
  { countryCode: "LK", countryName: "Sri Lanka" },
  { countryCode: "LI", countryName: "Liechtenstein" },
  { countryCode: "LV", countryName: "Latvia" },
  { countryCode: "TO", countryName: "Tonga" },
  { countryCode: "LT", countryName: "Lithuania" },
  { countryCode: "LU", countryName: "Luxembourg" },
  { countryCode: "LR", countryName: "Liberia" },
  { countryCode: "LS", countryName: "Lesotho" },
  { countryCode: "TH", countryName: "Thailand" },
  { countryCode: "TG", countryName: "Togo" },
  { countryCode: "TD", countryName: "Chad" },
  { countryCode: "LY", countryName: "Libya" },
  { countryCode: "VA", countryName: "Vatican" },
  { countryCode: "AE", countryName: "United Arab Emirates" },
  { countryCode: "AD", countryName: "Andorra" },
  { countryCode: "AF", countryName: "Afghanistan" },
  { countryCode: "IS", countryName: "Iceland" },
  { countryCode: "IR", countryName: "Iran" },
  { countryCode: "AM", countryName: "Armenia" },
  { countryCode: "AL", countryName: "Albania" },
  { countryCode: "AO", countryName: "Angola" },
  { countryCode: "AR", countryName: "Argentina" },
  { countryCode: "AU", countryName: "Australia" },
  { countryCode: "AT", countryName: "Austria" },
  { countryCode: "AW", countryName: "Aruba" },
  { countryCode: "IN", countryName: "India" },
  { countryCode: "AX", countryName: "Aland Islands" },
  { countryCode: "AZ", countryName: "Azerbaijan" },
  { countryCode: "IE", countryName: "Ireland" },
  { countryCode: "ID", countryName: "Indonesia" },
  { countryCode: "UA", countryName: "Ukraine" },
  { countryCode: "QA", countryName: "Qatar" },
  { countryCode: "MZ", countryName: "Mozambique" },
];

export const CountryCodeObject = {
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  WF: "Wallis and Futuna",
  BL: "Saint Barthelemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BT: "Bhutan",
  JM: "Jamaica",
  BW: "Botswana",
  WS: "Samoa",
  BQ: "Bonaire, Saint Eustatius and Saba ",
  BR: "Brazil",
  BS: "Bahamas",
  JE: "Jersey",
  BY: "Belarus",
  BZ: "Belize",
  RU: "Russia",
  RW: "Rwanda",
  RS: "Serbia",
  TL: "East Timor",
  RE: "Reunion",
  TM: "Turkmenistan",
  TJ: "Tajikistan",
  RO: "Romania",
  TK: "Tokelau",
  GW: "Guinea-Bissau",
  GT: "Guatemala",
  GR: "Greece",
  GQ: "Equatorial Guinea",
  GP: "Guadeloupe",
  JP: "Japan",
  GY: "Guyana",
  GG: "Guernsey",
  GF: "French Guiana",
  GE: "Georgia",
  GD: "Grenada",
  GB: "United Kingdom",
  GA: "Gabon",
  SV: "El Salvador",
  GN: "Guinea",
  GM: "Gambia",
  GL: "Greenland",
  GI: "Gibraltar",
  GH: "Ghana",
  OM: "Oman",
  TN: "Tunisia",
  JO: "Jordan",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  HK: "Hong Kong",
  HN: "Honduras",
  VE: "Venezuela",
  PS: "Palestinian Territory",
  PW: "Palau",
  PT: "Portugal",
  SJ: "Svalbard and Jan Mayen",
  PY: "Paraguay",
  IQ: "Iraq",
  PA: "Panama",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PE: "Peru",
  PK: "Pakistan",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  ZM: "Zambia",
  EH: "Western Sahara",
  EE: "Estonia",
  EG: "Egypt",
  ZA: "South Africa",
  EC: "Ecuador",
  IT: "Italy",
  VN: "Vietnam",
  SB: "Solomon Islands",
  ET: "Ethiopia",
  SO: "Somalia",
  ZW: "Zimbabwe",
  SA: "Saudi Arabia",
  ES: "Spain",
  ER: "Eritrea",
  ME: "Montenegro",
  MD: "Moldova",
  MG: "Madagascar",
  MF: "Saint Martin",
  MA: "Morocco",
  MC: "Monaco",
  UZ: "Uzbekistan",
  MM: "Myanmar",
  ML: "Mali",
  MO: "Macao",
  MN: "Mongolia",
  MH: "Marshall Islands",
  MK: "Macedonia",
  MU: "Mauritius",
  MT: "Malta",
  MW: "Malawi",
  MV: "Maldives",
  MQ: "Martinique",
  MR: "Mauritania",
  IM: "Isle of Man",
  UG: "Uganda",
  TZ: "Tanzania",
  MY: "Malaysia",
  MX: "Mexico",
  IL: "Israel",
  FR: "France",
  IO: "British Indian Ocean Territory",
  SH: "Saint Helena",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NA: "Namibia",
  VU: "Vanuatu",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NZ: "New Zealand",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  CK: "Cook Islands",
  CI: "Ivory Coast",
  CH: "Switzerland",
  CO: "Colombia",
  CN: "China",
  CM: "Cameroon",
  CL: "Chile",
  CC: "Cocos Islands",
  CA: "Canada",
  CG: "Republic of the Congo",
  CF: "Central African Republic",
  CD: "Democratic Republic of the Congo",
  CZ: "Czech Republic",
  CY: "Cyprus",
  CX: "Christmas Island",
  CR: "Costa Rica",
  CW: "Curacao",
  CV: "Cape Verde",
  CU: "Cuba",
  SZ: "Swaziland",
  SY: "Syria",
  SX: "Sint Maarten",
  KG: "Kyrgyzstan",
  KE: "Kenya",
  SS: "South Sudan",
  SR: "Suriname",
  KI: "Kiribati",
  KH: "Cambodia",
  KM: "Comoros",
  ST: "Sao Tome and Principe",
  SK: "Slovakia",
  KR: "South Korea",
  SI: "Slovenia",
  KP: "North Korea",
  KW: "Kuwait",
  SN: "Senegal",
  SM: "San Marino",
  SL: "Sierra Leone",
  SC: "Seychelles",
  KZ: "Kazakhstan",
  KY: "Cayman Islands",
  SG: "Singapore",
  SE: "Sweden",
  SD: "Sudan",
  DJ: "Djibouti",
  DK: "Denmark",
  VG: "British Virgin Islands",
  DE: "Germany",
  YE: "Yemen",
  DZ: "Algeria",
  US: "United States",
  UY: "Uruguay",
  YT: "Mayotte",
  UM: "United States Minor Outlying Islands",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LA: "Laos",
  TV: "Tuvalu",
  TW: "Taiwan",
  TT: "Trinidad and Tobago",
  TR: "Turkey",
  LK: "Sri Lanka",
  LI: "Liechtenstein",
  LV: "Latvia",
  TO: "Tonga",
  LT: "Lithuania",
  LU: "Luxembourg",
  LR: "Liberia",
  LS: "Lesotho",
  TH: "Thailand",
  TG: "Togo",
  TD: "Chad",
  LY: "Libya",
  VA: "Vatican",
  AE: "United Arab Emirates",
  AD: "Andorra",
  AF: "Afghanistan",
  IS: "Iceland",
  IR: "Iran",
  AM: "Armenia",
  AL: "Albania",
  AO: "Angola",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  AW: "Aruba",
  IN: "India",
  AX: "Aland Islands",
  AZ: "Azerbaijan",
  IE: "Ireland",
  ID: "Indonesia",
  UA: "Ukraine",
  QA: "Qatar",
  MZ: "Mozambique",
};
